'use client'
import { useMemo, useState } from 'react'
import { Search, MapPin, Heart, PawPrint, Plus, MessageCircle, Phone, Mail, X, ImagePlus, ShieldCheck, ChevronDown } from 'lucide-react'
import { FaInstagram, FaFacebookF, FaTiktok } from 'react-icons/fa6'

const pets = [
 {id:1,name:'Luna',type:'Cachorro',breed:'SRD',age:'2 anos',city:'Campinas, SP',sex:'Fêmea',desc:'Carinhosa, brincalhona e pronta para ganhar uma família.',img:'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85'},
 {id:2,name:'Thor',type:'Cachorro',breed:'Labrador',age:'4 anos',city:'Valinhos, SP',sex:'Macho',desc:'Companheiro, dócil e adora passeios ao ar livre.',img:'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=900&q=85'},
 {id:3,name:'Mimi',type:'Gato',breed:'SRD',age:'8 meses',city:'Campinas, SP',sex:'Fêmea',desc:'Curiosa, tranquila e muito apegada a pessoas.',img:'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=85'},
 {id:4,name:'Nino',type:'Gato',breed:'SRD',age:'1 ano',city:'Hortolândia, SP',sex:'Macho',desc:'Esperto e carinhoso. Se dá bem com outros animais.',img:'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=900&q=85'},
 {id:5,name:'Mel',type:'Cachorro',breed:'Beagle',age:'3 anos',city:'Indaiatuba, SP',sex:'Fêmea',desc:'Amor em quatro patas, cheia de energia e afeto.',img:'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=900&q=85'},
 {id:6,name:'Bento',type:'Cachorro',breed:'SRD',age:'5 meses',city:'Sumaré, SP',sex:'Macho',desc:'Filhote sociável procurando um lar com muito carinho.',img:'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?auto=format&fit=crop&w=900&q=85'}
]

export default function Home(){
 const [petList,setPetList]=useState(pets); const [query,setQuery]=useState(''); const [type,setType]=useState('Todos'); const [liked,setLiked]=useState([]); const [modal,setModal]=useState(null); const [contact,setContact]=useState(false); const [submitted,setSubmitted]=useState(false)
 const [photo,setPhoto]=useState(null)
 const filtered=useMemo(()=>petList.filter(p=>(type==='Todos'||p.type===type)&&`${p.name} ${p.breed} ${p.city}`.toLowerCase().includes(query.toLowerCase())),[petList,query,type])
 const toggleLike=id=>setLiked(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])
 const addPet=pet=>{setPetList(v=>[pet,...v]);setSubmitted(true);setModal(null);setPhoto(null)}
 return <main>
  <header className="nav"><div className="brand"><span className="brandmark"><PawPrint size={21}/></span><span>Doe ou Adote um Pet</span></div><nav><a href="#adote">Adote</a><a href="#doe">Doe um pet</a><a href="#como">Como funciona</a><a href="#contato">Contato</a></nav><button className="outline" onClick={()=>setModal('doar')}><Plus size={17}/> Cadastrar pet</button></header>
  <section className="hero"><div className="hero-copy"><div className="eyebrow"><Heart size={15} fill="currentColor"/> Amor que encontra um lar</div><h1>Um lar pode mudar<br/><em>duas vidas.</em></h1><p>Conectamos pets que precisam de uma família a pessoas prontas para oferecer carinho, cuidado e uma segunda chance.</p><div className="hero-actions"><a className="primary" href="#adote">Encontrar um pet <Search size={18}/></a><button className="ghost" onClick={()=>setModal('doar')}>Quero doar um pet</button></div><div className="trust"><ShieldCheck size={18}/><span>Comunidade moderada · Adoção responsável</span></div></div><div className="hero-art"><div className="blob"></div><img src="https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=1000&q=85" alt="Cachorro e gato juntos"/><div className="floating-card"><div className="mini-icon"><Heart size={18} fill="currentColor"/></div><div><strong>+2.400</strong><small>adoções realizadas</small></div></div></div></section>
  <section className="stats"><div><strong>2.400+</strong><span>pets adotados</span></div><div><strong>680</strong><span>pets esperando</span></div><div><strong>1.100+</strong><span>famílias cadastradas</span></div><div><strong>98%</strong><span>experiências positivas</span></div></section>
  <section className="listing" id="adote"><div className="section-head"><div><div className="eyebrow">ENCONTRE SEU COMPANHEIRO</div><h2>Pets esperando por você</h2></div><span className="result">{filtered.length} resultados</span></div><div className="filters"><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquise por nome, raça ou cidade..."/></div><div className="chips">{['Todos','Cachorro','Gato'].map(x=><button key={x} className={type===x?'chip active':'chip'} onClick={()=>setType(x)}>{x}</button>)}</div><button className="filter"><MapPin size={17}/> Campinas e região <ChevronDown size={15}/></button></div><div className="grid">{filtered.map(p=><article className="pet-card" key={p.id}><div className="photo-wrap"><img src={p.img} alt={p.name}/><button className={liked.includes(p.id)?'heart liked':'heart'} onClick={()=>toggleLike(p.id)}><Heart size={19} fill={liked.includes(p.id)?'currentColor':'none'}/></button><span className="tag">{p.type}</span></div><div className="pet-body"><div className="pet-title"><div><h3>{p.name}</h3><span>{p.breed} · {p.age}</span></div><span className="sex">{p.sex==='Fêmea'?'♀':'♂'}</span></div><div className="place"><MapPin size={15}/>{p.city}</div><p>{p.desc}</p><button className="card-btn" onClick={()=>setModal(p)}>Quero conhecer <span>→</span></button></div></article>)}</div>{filtered.length===0&&<div className="empty">Nenhum pet encontrado. Tente outro nome, raça ou cidade.</div>}</section>
  <section className="donate" id="doe"><div><div className="eyebrow">TEM UM PET PARA DOAR?</div><h2>Ajude seu pet a encontrar<br/>uma família especial.</h2><p>Publique gratuitamente com fotos, informações e seu contato. Nossa comunidade ajuda a aproximar histórias que combinam.</p><button className="primary" onClick={()=>setModal('doar')}>Cadastrar pet para adoção <Plus size={18}/></button></div><div className="donate-image"><img src="https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=1000&q=85" alt="Cachorro feliz"/></div></section>
  <section className="how" id="como"><div className="section-head center"><div><div className="eyebrow">SIMPLES E SEGURO</div><h2>Como funciona</h2></div></div><div className="steps"><div><span>01</span><PawPrint/><h3>Cadastre</h3><p>Publique o pet com fotos, história e informações importantes.</p></div><div><span>02</span><Search/><h3>Encontre</h3><p>Pesquise por localização, espécie, idade e perfil.</p></div><div><span>03</span><MessageCircle/><h3>Conecte</h3><p>Converse com o responsável e combine os próximos passos.</p></div><div><span>04</span><Heart/><h3>Adote</h3><p>Faça uma adoção consciente e transforme uma vida.</p></div></div></section>
  <footer id="contato"><div className="footer-brand"><div className="brand"><span className="brandmark"><PawPrint size={19}/></span><span>Doe ou Adote um Pet</span></div><p>Conectando pets e pessoas para criar histórias que duram uma vida inteira.</p></div><div><h4>Explorar</h4><a href="#adote">Encontrar pets</a><a href="#doe">Doar um pet</a><a href="#como">Como funciona</a></div><div><h4>Contato</h4><a href="mailto:oi@petamigo.com.br"><Mail size={15}/> oi@petamigo.com.br</a><a href="tel:+5519999999999"><Phone size={15}/> (19) 99999-9999</a></div><div><h4>Redes sociais</h4><div className="social-links"><a href="https://instagram.com" target="_blank" rel="noreferrer" aria-label="Instagram"><FaInstagram size={18}/><span>Instagram</span></a><a href="https://facebook.com" target="_blank" rel="noreferrer" aria-label="Facebook"><FaFacebookF size={18}/><span>Facebook</span></a><a href="https://tiktok.com" target="_blank" rel="noreferrer" aria-label="TikTok"><FaTiktok size={18}/><span>TikTok</span></a></div></div><div className="copyright">© 2026 Doe ou Adote um Pet. Feito com carinho para quem ama animais.</div></footer>
    {modal&&<div className="modal-bg" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button>{modal==='doar'?<DonateForm photo={photo} setPhoto={setPhoto} onSubmit={addPet}/>:<ContactModal pet={modal} onClose={()=>setModal(null)} onContact={()=>setContact(true)}/>}</div></div>}
  {contact&&<div className="toast"><div><strong>Mensagem pronta!</strong><span>O contato do responsável foi liberado para você.</span></div><button onClick={()=>setContact(false)}>Fechar</button></div>}
 </main>
}
function ContactModal({pet,onClose,onContact}){return <><div className="modal-label">PERFIL DO PET</div><h2>Conheça a {pet.name} 🐾</h2><div className="contact-profile"><img src={pet.img}/><div><h3>{pet.name}</h3><p>{pet.breed} · {pet.age} · {pet.city}</p><p>{pet.desc}</p></div></div><div className="notice"><ShieldCheck size={18}/><span>Converse com responsabilidade. Nunca faça pagamentos antecipados sem verificar o processo de adoção.</span></div><button className="primary full" onClick={onContact}><MessageCircle size={18}/> Quero falar com o responsável</button></>}
function DonateForm({photo,setPhoto,onSubmit}){const [form,setForm]=useState({name:'',type:'Cachorro',age:'',city:'',breed:'SRD',desc:''}); const update=e=>setForm(v=>({...v,[e.target.name]:e.target.value})); const submit=e=>{e.preventDefault();if(!photo||!form.name||!form.age||!form.city)return;onSubmit({id:Date.now(),...form,sex:'',img:photo})}; return <form onSubmit={submit}><div className="modal-label">NOVO ANÚNCIO</div><h2>Cadastre um pet para adoção</h2><p className="modal-sub">Preencha os dados para encontrar uma família responsável.</p><div className="upload"><label htmlFor="petphoto">{photo?<img src={photo} alt="Prévia"/>:<><ImagePlus size={26}/><strong>Adicionar foto do pet</strong><span>JPG ou PNG · até 5 MB</span></>}<input id="petphoto" type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setPhoto(URL.createObjectURL(f))}}/></label></div><div className="form-grid"><label>Nome<input name="name" value={form.name} onChange={update} placeholder="Ex.: Mel" required/></label><label>Espécie<select name="type" value={form.type} onChange={update}><option>Cachorro</option><option>Gato</option><option>Outro</option></select></label><label>Idade<input name="age" value={form.age} onChange={update} placeholder="Ex.: 2 anos" required/></label><label>Cidade<input name="city" value={form.city} onChange={update} placeholder="Ex.: Campinas - SP" required/></label><label>Raça<input name="breed" value={form.breed} onChange={update} placeholder="Ex.: SRD"/></label></div><label className="wide">Conte a história do pet<textarea name="desc" value={form.desc} onChange={update} placeholder="Temperamento, rotina, cuidados e o que uma família precisa saber..."></textarea></label><button className="primary full" type="submit">Publicar anúncio <Plus size={18}/></button></form>}
